# Generated by Django 5.1.7 on 2025-03-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Автор',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='Группа',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Название',
        ),
    ]
